### ISSUE TITLE
publish to OpenVSX

### ISSUE THREAD

**Issue by akosyakov** [PDConSec/vsc-print#120]
Unfortunately MS prohibits usages of MS marketplace by any other products or redistribution vsix files from it. Because of it we kindly ask you to take the ownership of your namespace in OpenVSX and publish there as well.

OpenVSX is a vendor neutral alternative to MS marketplace used by all other derivatives of VS Code like [Gitpod](gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), VSCodium, Theia based IDEs, and so on.

The docs for publishing the extension are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions. Technically this should be straightforward. You get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: [redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82](https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82)

Let me know if you are opened to a PR contributing release GH action both to MS marketplace and OpenVSX.

**Comment by matkoniecz** [comment]
note

> Non-standard versions of VS Code make up such a tiny portion of the user base that I cannot give this kind of installer problem priority over standard installations.

https://github.com/PeterWone/vsc-print/issues/116#issuecomment-926971005

**Comment by PeterWone** [comment]
What is really appreciated, @matkoniecz, is the fact that you took the trouble to figure out what was wrong, and you led me to discover that someone else was publishing a broken setup kit. I have been trying for a very long time to figure out why some people's installations were missing files.

**Comment by PeterWone** [comment]
@akosyakov oh I'm so sorry I need to read more carefully. I am indeed interested in such a PR, it only just dawned on me that "GH action" is a GitHub action in the context of CICD.

**Comment by akosyakov** [comment]
@PeterWone here you go: https://github.com/PeterWone/vsc-print/pull/121

**Comment by PeterWone** [comment]
Thank you very much.

**Comment by binaryben** [comment]
Just looking for clarification, does the merged PR mean that publishing to Open VSX is likely coming?

**Comment by PeterWone** [comment]
It does. I've been making a lot of changes in the lead up to the 1.0 release. Setting up to publish to OpenVSX is on the list.

**Comment by PeterWone** [comment]
Closed pending poll results

**Comment by matkoniecz** [comment]
> poll

How you can vote in it?

**Comment by PeterWone** [comment]
https://github.com/PDConSec/vsc-print/discussions/222
