### ISSUE TITLE
Add "Lightfair" colour scheme?

### ISSUE THREAD

**Issue by jlefeaux** [PDConSec/vsc-print#139]
Wondering if Lightfair could be added to the list of available color themes.  (It is a "light" theme.)

I like the colors it has for React components.

It sounds like a straightforward change. I would do it myself if I could, per the contributing guidelines, but I am not proficient enough.

**Comment by PeterWone** [comment]
It was actually present but needed to be added to the selection list. I sneaked it in with the new test suite.

**Comment by jlefeaux** [comment]
Woot! Thank you!
