### ISSUE TITLE
Print a selection is not working.

### ISSUE THREAD

**Issue by YRFT** [PDConSec/vsc-print#142]
The full-document print is working as expected.

But getting below error when I print a selection.

```
TypeError: Cannot read properties of undefined (reading 'asHtml')
    at g.<anonymous> (/home/bo/.vscode/extensions/pdconsec.vscode-print-0.9.26/dist/extension.js:2:1202382)
    at Generator.next (<anonymous>)
    at i (/home/bo/.vscode/extensions/pdconsec.vscode-print-0.9.26/dist/extension.js:2:1200323)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I reopened the vscode and the browser, but still the same.

**Comment by YRFT** [comment]
It's weird that when printing the files of other folders, this extension is working as expected. I think the problem is nothing to do with this extension. I'll close this issue.

Thank you for this awesome extension.

**Comment by PeterWone** [comment]
@YRFT I can reproduce this. You've definitely found a bug.

**Comment by YRFT** [comment]
Thank you for your work  on this.

**Comment by PeterWone** [comment]
@YRFT would you mind grabbing the latest release and confirming for me that printing of a text selection is now working for you? The issue was auto closed when I merged the fix, it works for me here but there's nothing like third party checks. If it's still not right I'll reopen it.

**Comment by YRFT** [comment]
I have installed the latest version of this extension. Printing a selection is working now. 

Thanks for your work.

**Comment by PeterWone** [comment]
Not at all. Thank _you_ for helping us find and fix problems, instead of simply leaving a bad review. My next action is to figure out how to check this in our integration tests (it's not the first time I've broken selection printing while working on other things).

**Comment by PeterWone** [comment]
Incidentally, if you decide to write a review after you've used it for a while, write the sort of review you'd hope to read if you were still choosing an extension. 

And if you have ideas for new features, don't be shy about opening an issue. Anything at all; if it's too hard I'll explain why and if it isn't then I'll credit you when it's released.

**Comment by YRFT** [comment]
OK. Thanks, again.
