### ISSUE TITLE
Does this work on vscode Version 1.70.2 on MacOS

### ISSUE THREAD

**Issue by MeestorX** [PDConSec/vsc-print#149]
I no longer see the printer icon, and when selecting print from the context menu, nothing happens. Have disabled and re-enabled as well as uninstalled and re-installed, still doesn't seem to be working.

Is there a log file somewhere that might help diagnose why it's not working?

**Comment by PeterWone** [comment]
I seem to have the same problem on 1.70.2 on Windows. I still see the printer icon but nothing happens when I try to print. Investigating.

**Comment by MeestorX** [comment]
No worries! I hadn't used it for a while, take your time.
When using VSCode-Insiders, (Version: 1.71.0-insider (Universal) I get this error when trying to print:
`Error while attempting to print: Command failed: xdg-open http://localhost:33983/529f2dbf-8dd6-45da-98b6-bf19a85e9fe6/ /bin/sh: 1: xdg-open: not found`
I get no error message when using the release version of VSCode.

**Comment by PeterWone** [comment]
`xdg-open` is the _Linux_ command for launching a URL in the default browser. Are you getting this message on OSX or Linux?

**Comment by MeestorX** [comment]
MacOS

**Comment by PeterWone** [comment]
Then there's something very strange going on. The code that decides which command is required looks like this

```
const browserLaunchMap: any = { darwin: "open", linux: "xdg-open", win32: "start" };
const cmd = browserLaunchMap[process.platform];
```

The actual implementation is a bit more complicated because it also considers the alternate browser settings.

```
public static getLaunchBrowserCommand(): string {
	const printConfig = vscode.workspace.getConfiguration("print", null);
	const cmd = printConfig.alternateBrowser && printConfig.browserPath ? escapePath(printConfig.browserPath) : browserLaunchMap[process.platform];
	return cmd;
}
```

You could try supplying the path to your browser and enabling it as the alternate browser, but `process.platform` is a vscode thing. The error you got implies that vscode is reporting the wrong platform, so something is really messed up.

**Comment by MeestorX** [comment]
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 20.6.0

**Comment by MeestorX** [comment]
Maybe to simplify things, I'll stick to troubleshooting "regular" VSCode. In that editor, I'm NOT SSH-ing into a linux box, but just editing code on my Mac.
On that setup, I get no icon and no error message or anything when I select "Print". It also doesn't print anything!

**Comment by PeterWone** [comment]
Remoting kind of explains it but not entirely. The UI anomalies you're experiencing are one the client side and this is also where the embedded webserver runs. Print uses the same remote file access API that vscode uses for editors. 

Come the weekend I will exercise Print on 1.70.2 in both local and ssh remote modes.

**Comment by PeterWone** [comment]
Could you please check this setting 

![image](https://user-images.githubusercontent.com/5498936/188252929-f8b3761c-b0b8-4fdc-8547-dab7f4cdd14f.png)

I think maybe the caption for this ought to be "Show the print icon above the active editor" 

At any rate make sure this is ticked. If it's off you won't see the printer icon when you make an editor active.

**Comment by MeestorX** [comment]
That item is checked.

**Comment by PeterWone** [comment]
Oh good, you're online. if you clone the repo and switch to the feature/diagnostics branch you won't have the log file but you will have enough to to the checks above and see the messages.

**Comment by PeterWone** [comment]
I seem to have the just released 1.71.0 on the Mac.

I can print files but there seems to be a problem printing an unsaved file. When I captured the About dialog details and pasted them in a new unsaved document the print icon was present but nothing visible happened when I clicked it.

This problem also occurs on Windows which makes it much less of a pain in the butt for me to debug.

**Comment by PeterWone** [comment]
Still no logging but grab the latest and turn on diagnostic messages. I fixed the issue with printing a never saved active editor.

**Comment by MeestorX** [comment]
Done, no change.
No icon, nothing happens when I select print using the context menu on a .js file.

**Comment by PeterWone** [comment]
Hmm...
OK I have tested 28 and 29 with vscode 1.71.0 on OSX Monterey without any problems other than the one I described and fixed. With Show diagnostics enabled, at the very least you should get a message about activation as soon as you focus an editor of a compatible activation language. 

Try launching code from Terminal with extensions disabled.

```
code --disable-extensions
```

and then interactively enable just Print. If it suddenly works then another extension is causing trouble.

**Comment by MeestorX** [comment]
I can't "enable" any extensions if I run using --disable-extensions, but I did try running code and then disabled all extensions except for Print and tried that.
Still no joy.
As I asked before, is there no logging available to help with debugging this module?

**Comment by PeterWone** [comment]
Logging - there will be shortly, I'm working on it.

Thank you for going to the trouble of disabling everything else to test.
I'm a bit poleaxed by this one given it doesn't happen on my test Mac, and really sorry that you're having so much grief with it.

**Comment by MeestorX** [comment]
Don't worry about it! I appreciate your help in solving this one. As a programmer myself, I know how difficult these sorts of problems can be to resolve remotely. The best thing that has helped me is detailed logging. With logs I can tell in a moment where the issue lies and then fix it.

**Comment by PeterWone** [comment]
It seems like log files aren't a thing for vscode extensions. You have to DIY. For your entertainment and edification, check this out https://www.javaer101.com/en/article/34164377.html

**Comment by PeterWone** [comment]
Logs! 

`Show Diagnostics` has been replaced by `Logging`. Enable `Logging` to, er, enable logging. You will find the logs in `~/.vscode/extensions/pdconsec.vscode-print-0.9.30/logs` and you're looking for the debug log.

If things were working normally and you started VS Code and printed a file they would look like this

```
2022-09-07 13:20:35 debug: Print activated
2022-09-07 13:20:54 debug: Print command was invoked
2022-09-07 13:20:54 debug: Creating a print session object for file:///d%3A/_free/vsc-print/package.json
2022-09-07 13:20:54 debug: Using the buffer of the active editor
2022-09-07 13:20:54 debug: Source code line numbers will be printed
2022-09-07 13:20:54 debug: Source code colour scheme is "Lightfair"
2022-09-07 13:20:54 debug: Platform detected as "win32" so launch browser command is "start"
2022-09-07 13:20:55 debug: Responding to base document request for session 7a3d5ce5-a9fd-4c76-adb0-4712915ba4f1
2022-09-07 13:20:55 debug: Printing d:\_free\vsc-print\package.json
2022-09-07 13:20:55 debug: Responding to vsc-print.resource request for default.css in session 7a3d5ce5-a9fd-4c76-adb0-4712915ba4f1
2022-09-07 13:20:55 debug: Responding to vsc-print.resource request for line-numbers.css in session 7a3d5ce5-a9fd-4c76-adb0-4712915ba4f1
2022-09-07 13:20:55 debug: Responding to vsc-print.resource request for colour-scheme.css in session 7a3d5ce5-a9fd-4c76-adb0-4712915ba4f1
2022-09-07 13:20:55 debug: Responding to vsc-print.resource request for settings.css in session 7a3d5ce5-a9fd-4c76-adb0-4712915ba4f1
2022-09-07 13:20:57 debug: Responding to "completed" request for session 7a3d5ce5-a9fd-4c76-adb0-4712915ba4f1
```

I suspect you won't even get `Print activeate` which is the root of all the other problems, but we'll see.

**Comment by MeestorX** [comment]
Good job!

Sadly, though, the log is completely blank. (As is the _info) file.

**Comment by PeterWone** [comment]
I'm not writing anything to the info log yet so that is to be expected. 

A completely blank log tells us several things.

* Since the log file was created the extension was definitely loaded.
* The loaded extension was the current version since the log code is new.
* The extension is not being activated by VS Code. 

All other problems are likely a consequence of the extension not being activated.

So... this version works on Windows, Linux and Mac in CICD and also on my actual Windows, Linux and Mac computers. This tells us that the extension code isn't completely busted though of course this doesn't mean it's flawless.

Presumably other extensions _do_ work or you would have mentioned this. At this point I would suggest disabling all the other extensions, but you already tried that. 

If you are willing, you can pull the repo and spin it up in the debug host. If you do that, in addition to `npm i` in the root of the project to pull dependencies you also need to make sure Gulp and gulp-cli are installed (using npm). 
To be honest `npm i` on its own _ought_ to suffice given that gulp cli is in the dev dependencies but I've had to fiddle with gulp on more than one occasion.

**Comment by DavidRawling** [comment]
Actually, I can confirm that the debug log for the released update doesn't show any events until the print icon is clicked. For example:

`2022-09-08 18:17:33 debug: Creating a print session object for <redacted>
2022-09-08 18:17:33 debug: Using the buffer of the active editor
2022-09-08 18:17:33 debug: Source code line numbers will be printed
2022-09-08 18:17:33 debug: Source code colour scheme is "Arduino"
2022-09-08 18:17:33 debug: Platform detected as "win32" so launch browser command is "start"`

**Comment by PeterWone** [comment]
That's what I get for last minute changes (renaming the setting). It wasn't changed everywhere in the code. All fixed now. There is no longer a logs folder, there's a single log file directly in the extension folder to which logs are appended. 

There is also a new command to open the log file

![image](https://user-images.githubusercontent.com/5498936/189145639-1e6bfa44-7c5b-4973-a5df-a7093aa25d4b.png)

Dave was right, there was a bug preventing activate from logging properly. Have another crack at it.

**Comment by MeestorX** [comment]
The command failed for me.

![image](https://user-images.githubusercontent.com/29129658/189185798-786df771-3b1e-4c13-92ea-cf0bf3ddc227.png)

Keep in mind that at no time have I ever seen the print icon on the menubar, so it's almost like the extension is failing before it even loads...

**Comment by PeterWone** [comment]
That only supports my belief that activate isn't being called.

Try it with VSCode Insiders. Based on other things you wrote, that one is at least activating.

**Comment by MeestorX** [comment]
Hey!! Works now on VSCode-Insiders!!!

But, sadly no joy on the regular one, even after following your suggested steps.

**Comment by PeterWone** [comment]
At this point the only thing I can think is that your VS Code installation suffered a faulty update to 1.70.2

You could close vscode and delete `~/.vscode` then start vscode but if you do that you will have to re-install all your extensions.

**Comment by kevinaangstadt** [comment]
I was also having this same issue on 1.71.0.  Going into settings, I noticed that Alternative Browser was checked, but no browser path was supplied.  I unchecked this option.  I also unchecked and re-checked the Editor Title Menu Button.  After reloading the window, print functionality (and the button) returned.

I think the Alternative Browser setting change was a red herring (I was about to re-check and printing continues to function), but it seems like something was corrupted with the Editor Title Menu Setting.  At least in my case, toggling the setting returned functionality.

**Comment by MeestorX** [comment]
> At this point the only thing I can think is that your VS Code installation suffered a faulty update to 1.70.2
> 
> Try this
> 
> 1. Close all instances of vscode
> 2. Rename `~/.vscode` to `~/.vscode_`
> 3. Start vscode, which should then behave like a new installation and create `~/.vscode`
> 4. Install Print and test it.

Nope. Something must be funky I guess with my vscode install. vscode-insiders works fine though, so I can use that for now. Be nice to know the cause however!

**Comment by MeestorX** [comment]
> I was also having this same issue on 1.71.0. Going into settings, I noticed that Alternative Browser was checked, but no browser path was supplied. I unchecked this option. I also unchecked and re-checked the Editor Title Menu Button. After reloading the window, print functionality (and the button) returned.

No joy.

**Comment by PeterWone** [comment]
@kevinaangstadt thank you for the extra info. Although the code already included a sanity check for the browser path before trying to use it, I have added code to explicitly check whether alternate browser is enabled without a browser path. The next release of Print for this on first load, explicitly resets the alternate browser checkbox and warns you, with the same warning going into the log for posterity.

![image](https://user-images.githubusercontent.com/5498936/189775948-8dc0f1aa-cd9d-4696-915e-1e4c3215c144.png)

**Comment by PeterWone** [comment]
@MeestorX Could you give me a copy of your VS Code app folder as a zip file and your `~/.vscode` folder as another zip file? 

I will try to use these to reproduce the problem on my Mac. If you don't want to post that publicly you can mail them directly to me at peter.wone@outlook.com

**Comment by MeestorX** [comment]
Don't sweat it, Peter. I can just use -insiders and get what I need for now. Thank you for your work on this!

**Comment by MeestorX** [comment]
For whatever reason, I just tried it today and it's back working. Maybe the Safari update? Dunno, but happy it works again!

**Comment by PeterWone** [comment]
Can't be Safari, the browser isn't involved till a print session is underway. You weren't even getting to the point of being able to launch one. But we know it was local to that installation of VS Code (because on the same computer it worked for Insiders). Have you had a new version of VS Code?
