### ISSUE TITLE
Printing from a WebviewPanel

### ISSUE THREAD

**Issue by alensiljak** [PDConSec/vsc-print#159]
Hi! Thanks for filling in for the missing bits in vscode with this extension.

I would like to have an ability to print the content from the HTML-rendering in a WebviewPanel. I have an [extension](https://github.com/alensiljak/abcjs-vscode) that is rendering a music score using abcjs in a webview, as a preview to the code being edited in the editor. Printing this output (mainly to PDF but some also may need to print on paper) would be a very welcome feature.

@PeterWone, thanks for the reply in the [VSCode printing issue](https://github.com/microsoft/vscode/issues/5953#issuecomment-1267863669) and for being ready to discuss this further!

**Comment by PeterWone** [comment]
I've been looking at how the ABCjs samples work. What I've seen so far generates SVG, but seems to be written with the expectation that it will run in a browser and operate directly on a DOM.

What I want to do is pass a string (the content of the editor) to the API and get another string back containing SVG markup. 

Do you know how to do that?

**Comment by alensiljak** [comment]
> Do you know how to do that?

This is exactly what I intend to try out today. I'm adding some settings that will control the abcjs options like `print: true/false` or `responsive: resize`, which are not a part of the ABC syntax. Then I would add a feature to export the rendered SVG as a file.
Paul pointed out quite a number of settings (i.e. `%%staffwidth`, `%%marginleft`, `%%scale`, etc.) that can be used to control the output so I would like to make these available as settings and experiment with the results.

**Comment by PeterWone** [comment]
Don't forget to render one svg per line

**Comment by alensiljak** [comment]
Thanks, that's a useful tip! The first iteration of settings have been implemented in v2.2. Now looking into SVG export.

**Comment by alensiljak** [comment]
ok, done! You can see the results in v2.3.0.

I will expand on this to perhaps place the SVG in a blank HTML page or something. This way all the formatting customizations from the editor are applied.
Perhaps there are some other tools that can be used. Let me know what you think. If a PDF generation would work directly in vscode, then perhaps passing the SVG to it would be a better option than generating an HTML and opening it in the browser?

**Comment by PeterWone** [comment]
Via the browser you get a familiar ui for paper selection, orientation and double side printing as well as headers and footers with meta data like document name and page numbers

**Comment by alensiljak** [comment]
Great tips! I have completed an initial version of export to Html, taking all of the above ideas. Now the exact rendering from the viewer is exported in Html.
The output already is comparable to my sheets in Lilypond. 🎆 
Thank you very much for support!

**Comment by PeterWone** [comment]
The requirement to run in the browser in order to fiddle the DOM is not really a good fit. The embedded webserver is expressly designed _not_ to be able to serve script. So I'm obliged to trawl through the abcjs code and figure out how to generate SVG directly.

**Comment by alensiljak** [comment]
I've managed to get a few options out. One of them being extracting the SVG into an offline HTML file and opening it in a browser - as opposed to serving it via HTTP. I'd expect this approach to run into more problems but so far it works for my use case.

I had another approach where I'd pass the ABC string into a print.html template, which would re-render it using abcjs. This I abandoned after exposing configuration settings which affect the layout. Then I no longer wanted to have two separate renderings but used the SVG from the rendering in the Preview panel.

This is an interesting learning exercise.

**Comment by PeterWone** [comment]
I have a branch that surfaces an API. You'll be able to register callbacks, and you can also trigger printing. In both cases I am registering commands. 

If you register print callbacks and _you_ trigger printing from a button on your webview after script updates your DOM, then all your getBodyHtml() callback has to do is return body.innerHtml

I don't know whether you need to also supply CSS. The API supports a callback for that too but I haven't tested that part yet.

**Comment by PeterWone** [comment]
Here's a [demo project](https://github.com/PDConSec/svg-print-demo) using the new API.

For this to work you need to build and install [this branch of Print](https://github.com/PDConSec/vsc-print/tree/feature/api).

**Comment by PeterWone** [comment]
I think this issue has been addressed as well as it can be, so I'm going to close it. The API branch is undergoing testing and will go live as soon as practical.
