### ISSUE TITLE
Print and Preview API

### ISSUE THREAD

**Issue by PeterWone** [PDConSec/vsc-print#164]
There are now _three_ sources of rendered documents. 

- Markdown
- abc music 
- Jupyter notebooks

It seems likely that there will be more.

Instead of Print working around the foibles of third party extensions and breaking whenever they make a change, it would be much more appropriate to publish an API for extensions to integrate themselves into Print and Preview in a uniform and documented way.

Print and preview are fundamentally similar; the document in question is rendered as styled HTML which is consumed either by a WebView panel or an external browser.  

The Print extension will register a command `Print.registerContentProvider` taking four parameters
- `getBodyHtml: (uri: vscode.Uri) => string`
- `getCssUriStrings?: () => string[]`
- `getTitle?: (filename: string) => string`
- `getResource?: (uri: vscode.Uri) => Buffer | string` 

All are callbacks. 
- `getBodyHtml` will be called by Print with a single parameter containing the source code (file or active editor document content) and must return HTML making up the content of the body of the HTML document being generated. 
- `getCssUriStrings` will be called by Print with no parameters and must return a string array of the CSS resources required. Link tags will be constructed and inserted in the head section of the HTML document being generated. If you don't supply it, no link tags will be added.
- `getTitle` is used to customise the title of the HTML page. This affects page headers when printing. If you don't supply it, a title will be derived from the URI of the document being printed.
- `getResource` takes the Uri of the resource, and returns a Buffer or string containing the content of a resource. Resources don't have to be textual, they can be binaries like images. The point of this is to allow Print's embedded webserver to serve resources bundled with your extension.

**Comment by PeterWone** [comment]
Both source code rendering and Markdown rendering have been re-implemented via this API. As a consequence of this dogfooding `getResource` now returns an `IResourceDescriptor` which includes the MIME type along with content (string or Buffer).

A demo implementation of an extension making use of the Print/Preview API handles SVG images. Print services as on parity with the pre-API codebase. Preview is functional but basic, only displaying the image. A bundled stylesheet scales the image to fit the available viewport.

Remaining work

* unit tests
* documentation
* placement of a print button on the preview pane

**Comment by PhiLhoSoft** [comment]
Another thing: (S)CSS files can render colors (native feature of VSC, I think).
Example:
![image](https://user-images.githubusercontent.com/1087902/203751657-3d14bd93-5feb-4db9-ae98-9b301fe8e5ec.png)
![image](https://user-images.githubusercontent.com/1087902/203751837-58afd4e1-f131-44cd-9a0c-bd55a65d4747.png)
Would be nice to be able to print these previews as well.

**Comment by PeterWone** [comment]
@PhiLhoSoft the point of going to all the trouble of crafting an API and checking usability is so that niche requirements can be serviced _by the people with the niche requirements._ You take care of special case transformation to HTML and I take care of how to print on multiple platforms and across platform boundaries and translating the UI into multiple languages. Remoting can involve two platforms, so there's six major combinations. Then there's managing UI and documentation updates in six languages. By contrast, I suspect a capable web developer could do the colour swatch thing with two CSS styles and an SVG inlined as a data url (one file).

But this is the one exception: it's a change to printing _source code_ which is handled by the built-in default renderer -- making it unsuitable for a third-party extension. So I'll add it to the backlog. 

While this can be done with two CSS styles and an SVG inline as a data URL, things are complicated by the need to do it after syntax highlight is applied. So don't hold your breath.

**Comment by PeterWone** [comment]
![image](https://user-images.githubusercontent.com/5498936/206707513-97fc024b-ff82-46db-bff0-591bff47d006.png)

It will be in the next release.

**Comment by PeterWone** [comment]
I'm closing this because the API work is complete. 

Release is delayed due to problems with alternate browser launch from remote workspaces.
