### ISSUE TITLE
FR: print a file without code highlights

### ISSUE THREAD

**Issue by StevenLi-DS** [PDConSec/vsc-print#167]
I find the extension to be very useful, and I have lots of long .log files which contains some statistical results. It would be great if I could just print a file without a highlight theme.

**Comment by StevenLi-DS** [comment]
I just realized that you can just select the file type to be plain text in vscode to print it without code hightlights
![CS-KRwv2h5v](https://user-images.githubusercontent.com/33796896/198857241-3784b6e3-5e7a-4438-9060-92bb3b0f475f.png)

**Comment by PeterWone** [comment]
Glad you found a solution. I was going to suggest changing the file extension but your answer is even better.

I was thinking of adding a how to section to the manual. This will make a good start.
