### ISSUE TITLE
Can't print latex math formulae in markdown

### ISSUE THREAD

**Issue by deanjiang** [PDConSec/vsc-print#175]
For example, the content of md file is:

$$ \hat{A}_t^{GAE(\gamma, \lambda)}=\sum_{l=0}^{\infin}(\gamma\lambda)^l \delta_{t+l}^V $$

and the printed page looks like this, with raw latex code and some converted symbols

\hat{A}_t^{GAE(\gamma, \lambda)}=\sum_{l=0}^{\infin}(\gamma\lambda)^l \delta_{t+l}^V
A^tGAE(γ,λ) = l=0∑∞(γλ)lδt+lV

**Comment by PeterWone** [comment]
Sorry about the slow response. It's a Christmas thing. 

If _some_ of the symbols are being rendered but not others it may be a limitation of the KaTex extension. Does it render properly in the Markdown preview pane? As soon as I have a chance I will check this myself, but essentially if it's broken in the preview pane then it's a KaTeX problem and I won't be able to do anything about it, whereas if it works in the preview pane then it's a Print problem that I can debug and fix.

**Comment by PeterWone** [comment]
If you find that this resolves the problem, please say so and close the issue. Otherwise, let me know what happens on your system.
