### ISSUE TITLE
Printing not working with alternate browser path

### ISSUE THREAD

**Issue by BlockyTheDev** [PDConSec/vsc-print#176]
I inserted the browser path to msedge.exe in the browser path field. The extension was installed with alternate browser in ticked state and an empty browser path and so it used chrome.exe because firefox.exe is my default browser. It also isn't working when I insert the path to chrome.exe or firefox.exe (I am not understanding why Firefox is not recommended. The thing with closing the window after printing is working!).
<img width="680" alt="image" src="https://user-images.githubusercontent.com/86119630/209975666-58480fb3-b335-438d-a817-00e35b00e87d.png">

When I press the Print-Button it isn't working and in the dev tools this warnings and error shows:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/86119630/209975502-7a38361b-d169-451e-a826-348063cb97ba.png">

**Comment by PeterWone** [comment]
Thanks for bringing this to my attention. No doubt this is a casualty of the extensive refactoring done to support the new API, and unfortunately alternate browser is one of the things I can't test with the current CICD setup.

**Comment by PeterWone** [comment]
There are two things going on here. One is normal behaviour that you haven't understood and the other is a straight-up bug.

The code in question looks like this

```ts
async function launchAlternateBrowser(url: string) {
	logger.debug("Alternate browser is selected");
	const printConfig = vscode.workspace.getConfiguration("print");
	const isRemoteWorkspace = true;// !!vscode.env.remoteName;
	const forceUseAgent = true;
	if (forceUseAgent || isRemoteWorkspace) {
		logger.debug(`forceUseAgent=${forceUseAgent}, isRemoteWorkspace=${isRemoteWorkspace}`)
		try {
			const cmds = await vscode.commands.getCommands(true);
			const isBrowserPathDefined = !!vscode.workspace.getConfiguration("print").browserPath;
			if (isBrowserPathDefined) {
				logger.debug("Browser path is defined, attempting to command remote browser agent");
				vscode.commands.executeCommand("print.launchBrowser", url);
			} else {
				const msg = "Alternate browser cannot be used because browser path has not been supplied. The default browser is being used.";
				logger.warn(msg);
				vscode.window.showWarningMessage(msg);
				vscode.env.openExternal(vscode.Uri.parse(url));
			}
		} catch {
			const msg = "The remote printing agent is not answering. As a result the default browser has been used."
			logger.warn(msg);
			vscode.window.showWarningMessage(msg);
			vscode.env.openExternal(vscode.Uri.parse(url));
		}
```

When running in the remote host it tries to invoke a command registered by a companion extension that launches the browser on your workstation. Microsoft broke the underlying mechanism by which this works (the proxying of commands from remote to local) and I've been doing quite a bit of work in this patch of code. So I have a little switch to fake remote behaviour for testing purposes.

Look at this

![image](https://user-images.githubusercontent.com/5498936/210157364-98cdf64f-d73e-44f4-98db-add157baef0d.png)

_Someone_ forgot to clean up. I will release a build shortly.

**Comment by BlockyTheDev** [comment]
> There are two things going on here. One is normal behaviour that you haven't understood and the other is a straight-up bug.
> 
> The code in question looks like this
> 
> ```ts
> async function launchAlternateBrowser(url: string) {
> 	logger.debug("Alternate browser is selected");
> 	const printConfig = vscode.workspace.getConfiguration("print");
> 	const isRemoteWorkspace = true;// !!vscode.env.remoteName;
> 	const forceUseAgent = true;
> 	if (forceUseAgent || isRemoteWorkspace) {
> 		logger.debug(`forceUseAgent=${forceUseAgent}, isRemoteWorkspace=${isRemoteWorkspace}`)
> 		try {
> 			const cmds = await vscode.commands.getCommands(true);
> 			const isBrowserPathDefined = !!vscode.workspace.getConfiguration("print").browserPath;
> 			if (isBrowserPathDefined) {
> 				logger.debug("Browser path is defined, attempting to command remote browser agent");
> 				vscode.commands.executeCommand("print.launchBrowser", url);
> 			} else {
> 				const msg = "Alternate browser cannot be used because browser path has not been supplied. The default browser is being used.";
> 				logger.warn(msg);
> 				vscode.window.showWarningMessage(msg);
> 				vscode.env.openExternal(vscode.Uri.parse(url));
> 			}
> 		} catch {
> 			const msg = "The remote printing agent is not answering. As a result the default browser has been used."
> 			logger.warn(msg);
> 			vscode.window.showWarningMessage(msg);
> 			vscode.env.openExternal(vscode.Uri.parse(url));
> 		}
> ```
> 
> When running in the remote host it tries to invoke a command registered by a companion extension that launches the alternate browser on your workstation. The companion extension may not be present and in that case the error you reported will occur. In that event it's supposed to fall back to launching the default browser. I hope this is the behaviour you experienced. If it wasn't, please let me know.
> 
> Microsoft broke the underlying mechanism by which this works (the proxying of commands from remote to local) and I've been doing quite a bit of work in this patch of code. So I have a little switch to fake remote behaviour for testing purposes.
> 
> Look at this
> 
> ![image](https://user-images.githubusercontent.com/5498936/210157364-98cdf64f-d73e-44f4-98db-add157baef0d.png)
> 
> _Someone_ forgot to clean up. I will release a build shortly.

Thanks for the detailed insight and explanation. I just wrote it down because I mainly develop in Python and Java and not in JavaScript and so I didn't looked into the code and posted everything about this topic what I found and maybe could have helped fixing the problem...

**Comment by PeterWone** [comment]
I wish more people would give high quality issue details like this. I wouldn't have figured it out so fast without the information you provided.

I'm going to close the issue because I've already fixed this on the branch I'm working on, but I have other work to complete before I can roll out an update.

**Comment by PeterWone** [comment]
Incidentally what version of Firefox are you using that closes the browser properly after printing?

**Comment by BlockyTheDev** [comment]
> In that event it's supposed to fall back to launching the default browser. I hope this is the behaviour you experienced. If it wasn't, please let me know.

If you mean the thing with "Alternate Browser" ticked and no "Browser Path" set it fell back to Chrome, which I have installed but is NOT my default browser (It is Firefox) but if you mean the situation with not opening a browser with a right path set then he opened no default browser.

> Incidentally what version of Firefox are you using that closes the browser properly after printing?

I used the stable version `108.0.1 (64-Bit)` and the developer edition `109.0b7 (64-Bit)`

**Comment by PeterWone** [comment]
> it fell back to Chrome, which I have installed but is NOT my default browser

VS Code thinks it is. Why that should be so is a question for the ages.

**Comment by BlockyTheDev** [comment]
> VS Code thinks it is. Why that should be so is a question for the ages.

After reinstalling the extension and my system it is opening the right default browser. Maybe it was a thing from VsCode or Windows 11 yesterday.
