### ISSUE TITLE
Some files with a .php extension are not printing in color.  

### ISSUE THREAD

**Issue by diggee17** [PDConSec/vsc-print#177]
Hi,  I love this extension because I'm "old school" and I like to review my code on paper.   I'm noticing that some files with  a .php extension are not printing in color.   I thought it was only files in sub folders but it isn't consistent.  I can't figure out the issue. 
The zip file contains a single file  "article copy.php".  This is a simple file that I have from a tutorial I'm following.  
Thanks.

[article copy.zip](https://github.com/PDConSec/vsc-print/files/10339044/article.copy.zip)

**Comment by PeterWone** [comment]
This is a mystery but I have at least managed to reproduce the problem, and investigating has revealed another issue.

**Comment by PeterWone** [comment]
Print relies on `highlightjs` for syntax colouring of the hundreds of different languages that people edit with VS Code. It would appear that there is a breaking change in the way `highlightjs` reacts to an invalid language identifier. 

The language identifiers VS Code uses are mostly but not always the same as the ones that `highlightjs` uses. Essentially, Print tries the VS Code language identifier and handles an error by trying again with highlightjs in "auto" mode. But `highlightjs` no longer throws an error when we give it an unrecognised language identifier, it now returns the source code escaped for HTML. 

I have updated Print to explicitly check whether any syntax colouring has been applied and if not then retry in auto mode. It seems to have fixed the problem and will appear in the next release.
