### ISSUE TITLE
ERR_SSL_Protocol_ERROR in Chrome

### ISSUE THREAD

**Issue by JustMeLC** [PDConSec/vsc-print#180]
Receive the following message in Chrome when trying to use the Print extension.

![image](https://user-images.githubusercontent.com/16749716/215095408-5232199f-5fec-4faf-8afd-bb31a8b49e23.png)

Current VS Code Info:

![image](https://user-images.githubusercontent.com/16749716/215095626-99680b9c-d004-45e4-bf74-9c1eb10cefac.png)

**Comment by PeterWone** [comment]
Your browser is configured to require SSL from localhost. Don't do this. You don't need SSL when connecting to your own computer, and if we implemented https we would have to maintain and install a certificate. This would cause problems for technically challenged users with no benefit to anyone.
