### ISSUE TITLE
Unexpected commas

### ISSUE THREAD

**Issue by Shu-Ting-Huang** [PDConSec/vsc-print#183]
I am trying to print https://github.com/PDConSec/vsc-print/blob/b9e63b7274746246e2236d62e63c450998d05f28/src/html-renderer.ts
However, I found unexpected commas on lines 14-19. As shown below
![2023-02-20_14-49-55](https://user-images.githubusercontent.com/57234743/220188369-619f3f68-50f0-44c3-80e9-e325ccbbfa78.png)

**Comment by PeterWone** [comment]
Thank you for reporting this.

That is the oddest bug I've seen all year. I'll look into it this evening after work.
________________________________
From: Shu-Ting Huang ***@***.***>
Sent: Tuesday, 21 February 2023 05:51
To: PDConSec/vsc-print ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PDConSec/vsc-print] Unexpected comma appears (Issue #183)


I am trying to print https://github.com/PDConSec/vsc-print/blob/b9e63b7274746246e2236d62e63c450998d05f28/src/html-renderer.ts<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPDConSec%2Fvsc-print%2Fblob%2Fb9e63b7274746246e2236d62e63c450998d05f28%2Fsrc%2Fhtml-renderer.ts&data=05%7C01%7C%7Cf7fca4469e944c8acbcf08db137bd623%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638125194831022558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aW4tokvppP8A97gqirJhHIJCk0U9itGHxwas7ObfA6o%3D&reserved=0>
However, I found unexpected commas on lines 14-19. As shown below
[2023-02-20_14-49-55]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F57234743%2F220188369-619f3f68-50f0-44c3-80e9-e325ccbbfa78.png&data=05%7C01%7C%7Cf7fca4469e944c8acbcf08db137bd623%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638125194831022558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E9ELdkdixerbI%2B4fbW%2Bg7Q5E5%2BBwNO270F5pk%2F3Csro%3D&reserved=0>
