### ISSUE TITLE
Print Filepath at top for file/selection in file (not folder)

### ISSUE THREAD

**Issue by ryanwwest** [PDConSec/vsc-print#184]
I'd like the option to print the full filepath (including filename) just before the first line of the PDF pages produced (so it has no line number). While this would ideally be controlled directly in headings, I understand that https://github.com/PDConSec/vsc-print/issues/163 is difficult to fix and having a more controllable 'heading' (being the first line (or more if filepath must wrap)) would be helpful. This seems to be possibly already supported for when printing via folders, but not for individual files or parts of files. The following configurations on this would be helpful:
- Specify absolute path, relative path (to the opened folder in VS Code), or filename only (a fourth option to specify relative to a given directory would be nice too but is too much to ask for now).
- Option to keep on every page or just first page.
- (less important) Show on top or bottom or page

**Comment by PeterWone** [comment]
This would be easy to do for first page only, and a lot harder to do at the top of every page for the same reason as with headers and footers: you have to take over pagination. 

The big problem with taking over pagination is controlling the browser -- I'd have to disable headers and footers, and set page size, orientation and margins. It's possible to do this but this is a whole can of worms because it's non-trivial and browser-specific.

**Comment by ryanwwest** [comment]
Makes sense. The every page vs first page was a bit of an afterthought - if we had the option for the first page alone I think that would still be very valuable (especially since it could be tuned to match absolute vs. relative which at least Chrome's headers and footers don't allow).

**Comment by PeterWone** [comment]
I actually do have ambitions of ~world domination~ full page layout control which is why my response was so specific. It revolves around paged.js and some extra work I've already piloted. The remaining issues are basically what I outlined above managing browser configuration.

**Comment by ryanwwest** [comment]
Out of curiosity, could you just disable the headers/footers in any browser/printing program desired (possibly via an API flag so the user doesn't have to find the option, but not really necessary) and completely control the margins and pagination on your own? Maybe you already said this above which is why it would be complex.

Is the current setup instead that the plugin pipes the code into another program that handles this, but then it's up to that program to determine margin details? It would be neat if this plugin could just print directly or even produce a PDF (which needs its own margin info), but that's thinking way ahead.

**Comment by PeterWone** [comment]
I have implemented first-page file-path header as an option in the course of addressing #188. I'll add it for selections in the next release.
