### ISSUE TITLE
Print error

### ISSUE THREAD

**Issue by et477** [PDConSec/vsc-print#187]
Hi, cant print anymore in VS. I get this error:
Command failed:  http://localhost:63360/3acbfe02-26de-4b6a-a231-f45ec6e1cbbf/
'http:' is not recognized as an internal or external command,
operable program or batch file.
It used to work. I did reinstall the Print extension, started VS again with no success. 
Any solution? Thank you. ET

**Comment by PeterWone** [comment]
Which operatiing system?
Are you using the default or the alternate browser?
What does it say in your log file?

**Comment by et477** [comment]
Hi Peter, Yes I am on W10. (Version 21H2, OS build 19044.2604)
I did untick "Use the alternate browser" and it does work now. Great.
Must be a default setting. Never went into settings.
Thx for your quick reply.

**Comment by PeterWone** [comment]
There was indeed a bug in the checking for alt browser path. In future releases this situation will produce the following warning and printing will succeed.

![image](https://user-images.githubusercontent.com/5498936/221441499-c684a307-649e-474a-b471-9abd1e402aeb.png)

**Comment by et477** [comment]
Awesome.

**Comment by PeterWone** [comment]
Actually that release is now, all credit to you. Because you said you didn't alter your settings I checked package.json and it was forcing alt browser to true. That would be affecting EVERYONE so I fixed the settings, fixed the check and pushed an emergency release. Thank you for finding it.
