### ISSUE TITLE
Print file name not including folder name

### ISSUE THREAD

**Issue by StevenLi-DS** [PDConSec/vsc-print#188]
Every time I run the cmd to print a file, and it will be opened in my Chrome. If I click save, the filename will also include the folder name in which the file is located with a prefix of `_..._`.
![CS-a0gKPeWs@2x](https://user-images.githubusercontent.com/33796896/221448188-c95dacb7-1da1-4501-9b73-c813cf25277b.png)

I didn't find a way to adjust it in the settings. Am I missing something?

**Comment by PeterWone** [comment]
This is the behaviour of Chrome when you save to PDF: it uses the page title. The page title has been shortened to "D:\...\folder-containing-file\file.name" to guarantee that the file name is not clipped when you print with headers. 

This is not currently subject to a user setting but it could be done. However, if you did this, it would mess up the header for every page, whereas you only have to edit the name once when saving to PDF. A possible solution would be to set the title to just the file name (no path at all).

How about a setting like this?

**Page title when printing source code:**
This affects the default file name when saving to PDF.
(combo box list)
- File name eg something.txt
- File path eg C;\potentially\a\really\long\path\containing\something.txt
- Abbreviated file path eg C:\...containing\something.txt

**Comment by StevenLi-DS** [comment]
Hi @PeterWone.  Thank you for the detailed explanation. I always print without header, so didn't realize that. I think your proposed settings make sense for me.

**Comment by PeterWone** [comment]
I've figured out how to please everyone. These are default settings in the next release.

![image](https://user-images.githubusercontent.com/5498936/222003767-d364437d-6385-422c-9f21-999de5f36226.png)

**Comment by ryanwwest** [comment]
Thanks for this @PeterWone. Would it be easy to add a fourth option to specify a relative filepath being relative to the top directory of the currently opened folder in VS Code?

**Comment by PeterWone** [comment]
![image](https://user-images.githubusercontent.com/5498936/222422454-3e22300c-0418-4827-b239-c318554c74b0.png)
