### ISSUE TITLE
"Running the contributed command: 'vsc-print.print' failed." when trying to print on Ubuntu

### ISSUE THREAD

**Issue by MrSurly** [PDConSec/vsc-print#193]
Per the title:

* Install extension
* Open `.md` file
* Click on the print icon

![image](https://user-images.githubusercontent.com/395016/222978077-06a2cc19-f510-4a33-87cf-1cc158bdb4cc.png)

I couldn't find any other error logs or messages other than the popup shown above.  Ubuntu 22.04.2 LTS.

**Comment by PeterWone** [comment]
Thank you for reporting this. I'll investigate after work.

**Comment by PeterWone** [comment]
Our CICD release pipeline runs tests on Linux, OSX and Windows, but just to be sure, I spun up a VM and put Ubuntu on it. As you can see it worked without issue. 

![image](https://user-images.githubusercontent.com/5498936/223101285-0349091f-cb46-4167-ba44-d9882375968c.png)

**Comment by PeterWone** [comment]
@MrSurly I think this is local to your installation so I'me going to close the issue. But if you find more evidence, especially something actionable, please don't hesitate to post it here and I'll reopen the issue to investigate further.
