### ISSUE TITLE
How to remove the file path as document heading?

### ISSUE THREAD

**Issue by Yaiphaba-Ng** [PDConSec/vsc-print#198]
The setting print.filepathAsDocumentHeading does not have an option to turn it off completely.
The deprecated [PrintCode](https://github.com/nobuhito/vscode.printcode) had it off by default.

**Comment by jj1bdx** [comment]
The file path must be able to be removed; otherwise this extension becomes completely useless.

**Comment by PeterWone** [comment]
There are three related settings.

![image](https://user-images.githubusercontent.com/5498936/225435721-7f2a696e-8a82-400e-8734-bd67792871b1.png)

Whether something is "completely useless" depends on individual requirements.

**Comment by PeterWone** [comment]
It appears the setting **Filepath Heading For Individually Printed Documents** is not being respected. This is a bug and will be fixed shortly.

**Comment by PeterWone** [comment]
0.11.1 respects the setting

**Comment by jj1bdx** [comment]
@PeterWone confirmed 0.11.1 fix. Thanks!
