### ISSUE TITLE
Internal Links

### ISSUE THREAD

**Issue by tv-weiske** [PDConSec/vsc-print#200]
Hello,

first of all, thank your for this VS Code extension! I noticed that internal links are not working in the exported pdf file. Currently, they are linking to a `localhost` address, hence the document is full of "broken" links. E.g., it would be great that if I click on a chapter in the table of contents, that it would jump directly to the chapter in the document - as you normally can in pdf files. In case this is not possible, maybe add an option to remove internal links in the export?

Regards.

P.S.: If possible, in the future, it would also be a great feature to export to html only (where internal links work, i.e. anchors).

**Comment by PeterWone** [comment]
You raise an excellent point. 

Support for links that export to PDF is problematic. Links have to refer to the embedded webserver to get resources like images and stylesheets. Making relative links would probably do it, the problem would be determining which form to use.

Export in general is done by the browser. 
* Export to PDF is baked-in. 
* There are extensions for Chrome and for Edge that will export to MHTML.

**Comment by PeterWone** [comment]
@tv-weiske could you supply a sample set? 

To upload multiple files in relative locations, prepare a folder possibly with subfolders, make a zip file of the folder and drag the zip file onto your reply to this.

**Comment by PeterWone** [comment]
Try this special build which suppresses the target="_blank" that the rendering pipeline was adding. 

https://github.com/PDConSec/vsc-print/releases/tag/release/0.11.2

It works for me with an auto TOC. If you still have problems I will need details and test documents. Otherwise it can be released.

**Comment by PeterWone** [comment]
This went out with release 0.11.3 

If it doesn't resolve this issue say so and we can re-open it
