### ISSUE TITLE
Markdown with LaTeX Maths shows duplicate

### ISSUE THREAD

**Issue by Nathanwoodburn** [PDConSec/vsc-print#201]
When printing markdown with LaTeX expressions vs print shows duplicate. It shows the LaTeX with formatting, and then just plain text.
For example on the print page:
![image](https://user-images.githubusercontent.com/62039630/230262858-362ed3dd-61bd-4022-8669-1bb048e187c0.png)
In the preview panel of VS code:
![image](https://user-images.githubusercontent.com/62039630/230262935-c64f0f0f-ef20-4a7f-9a78-aaf8ba21179c.png)

And the actual markdown code is
```
$(X_i)_{1..8} = (X_{π(i)})_{1..8}$ where $\pi = \left(\begin{array}{cccccccc} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\end{array}\right)$
```

**Comment by Nathanwoodburn** [comment]
I've just had a look and there are two html spans.
![image](https://user-images.githubusercontent.com/62039630/230264449-daccc11c-09e0-4ac8-b95e-9602e1fd0fe2.png)
As a quick fix you can just add a CSS rule like so
```
span.katex-html {
    display: none;
}
```
![image](https://user-images.githubusercontent.com/62039630/230264630-447cb81f-1f50-41ae-bd7f-ca79d30d402e.png)

**Comment by PeterWone** [comment]
Nathan, thank you for your help. I'm not ignoring you, I've been out in the bush for nearly a month building sheds! I'm back now, but as you can imagine I'm playing catch up at work. 

I'm trying to get several bugfixes ready for a minor release but it may not happen for a few weeks.

**Comment by PeterWone** [comment]
I'm not seeing this problem. 
![image](https://github.com/PDConSec/vsc-print/assets/5498936/7fa5705b-c975-48d7-a3ad-d3bbbf9afbc8)

# However

I suspect this may be a consequence of fixing a different problem. VS Code was embedding a style block into the HTML emerging from the rendering pipeline. This is a rather antisocial thing to do as it cannot be overridden by a linked stylesheet, so I was excising it. The logic to find the bounds of the <style> block was faulty and under some circumstances it was removing too much. 

This is fixed now and I'm not experiencing the problem so I'm closing the issue but if you still experience the issue let me know and I'll re-open it.
