### ISSUE TITLE
SVG images won't be shown when printing a markdown document

### ISSUE THREAD

**Issue by skystar0227** [PDConSec/vsc-print#205]
Thank you very much for this great vscode extension.

I have seen a problem with SVG images in a markdown.

Current behavior: SVG image references in a markdown document are not rendered in a print preview.

Expected behavior: Their images can be seen in a print preview.

Possibly related issue: I think that content type for SVG images should be "image/svg+xml" instead of "image/svg".

https://github.com/PDConSec/vsc-print/blob/dcde65a704bdca760baf3c2f1e2fb77983aa734e/src/print-session.ts#L230

**Comment by PeterWone** [comment]
You are definitely right about the mime type for SVG and probably right about this being the root of the problem.
