### ISSUE TITLE
Context menu for file explorer does not respect Print item position setting

### ISSUE THREAD

**Issue by nopeless** [PDConSec/vsc-print#208]
I have checked both user settings and workspace settings, both are set to bottom, but print still shows on top. Is this only affecting me?

**Comment by PeterWone** [comment]
Thank you for reporting this. As this is entirely done with settings it is impossible to catch in with a unit test. 

It used to work, but I can reproduce the problem so I suppose the way VS Code handles this must have changed. I'll look into it.

**Comment by PeterWone** [comment]
Actually no, it does work... on my system, at least. Read on, and then check your system to see whether this is the problem.

So once upon a time there was only the **editor** context menu. And that's what the setting controls.
![image](https://github.com/PDConSec/vsc-print/assets/5498936/0e67dfdc-3960-4753-a3e5-5808b74d9db7)

Then features were added and there was also a context menu for the file explorer pane. _That_ menu doesn't take any notice of the position setting.

If you think that the setting needs to be renamed slightly and both menus should respect it, then you'll be pleased to hear that I agree with you. Of course, if it's not working in the editor menu that's another matter and we'll look into it.

**Comment by nopeless** [comment]
Ah, i am referring to the file system context menu

I keep hitting print when I want to create a new file so it has been bugging me a lot. 

What would be a solution?

**Comment by PeterWone** [comment]
You could hack your `package.json` file and make it depend on the same setting. I'm at work right now, I'll sort something out this evening

**Comment by PeterWone** [comment]
Probably the quickest thing would be to disable Print in the extensions list, enable/disable is pretty quick.

**Comment by PeterWone** [comment]
This change to `package.json` will turn up in the next release, but you can patch your installation by editing the file as shown. The left-hand side is what you'll have, the right-hand side shows how it should be when you're finished. Assuming you are using Windows you will find the file in `%userprofile%\.vscode\extensions\pdconsec.vscode-print-0.11.1`

![image](https://github.com/PDConSec/vsc-print/assets/5498936/4f8288b1-d2b3-47b7-9a5f-d4b1bba1005a)

Here it is as text so you can copy and paste insteading of typing all that.

```json
				{
					"when": "ecmPrint == Top",
					"command": "vsc-print.print",
					"group": "navigation"
				},
				{
					"when": "ecmPrint == Bottom",
					"command": "vsc-print.print",
					"group": "Z_commands"
				}
```

Once you've applied the patch you will find that the file explorer context menu also respects the setting.

![image](https://github.com/PDConSec/vsc-print/assets/5498936/6b243e74-c0e8-43a1-8e96-8b9d1e7a72a8)

**Comment by nopeless** [comment]
Thanks 👍
