### ISSUE TITLE
Trouble w Alternate Browser Path on macOS. Probably something I'm (not) doing.

### ISSUE THREAD

**Issue by joeballard** [PDConSec/vsc-print#209]
I'm on macOS Ventura, default browser is Safari. 
Trying to set up Chrome as the alternate browser. 

- Followed the advice to use a shell script to launch Chrome. 
- But what I have so far launches Chrome (blank) but does not render the file. 
- I have a shell script `launch-chrome.sh`
- It's content is: `open -a "Google Chrome"` 
- Browser Path setting is `~/launch-chrome.sh`
- So it launches Chrome, but blank, no rendered document.
- I assume I'm missing something in my shell script

**Comment by PeterWone** [comment]
Hi Joe. 

I've been busy with working and also building a cabin in the woods so I haven't been keeping up with things. Thank you for the detailed report, I have a Mac now so I'll test this.

**Comment by PeterWone** [comment]
I did some research based on everything said so far.

* OSX bash supports `$@`
* `open -a "application name" is the correct way to do this for OSX

Edit your file to contain 

```bash
open -a "Google Chrome" $@
```

That should work. Please let me know if there are any problems.

**Comment by joeballard** [comment]
Adding the '$@' worked fine. Thanks!! And good luck with the cabin in the woods.
