### ISSUE TITLE
Is it possible to extract the core of code and make it as an independent library and executable program?

### ISSUE THREAD

**Issue by 0400H** [PDConSec/vsc-print#268]
If not rely on vscode and make the core of code as an independent application, it will have richer usage scenarios.

For example, just use config file and command line to generate PDF.

**Comment by PeterWone** [comment]
PanDoc

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PDConSec/vsc-print/issues/268#issuecomment-1871733476

@PeterWone, what does merely "PanDoc" mean as a response to https://github.com/PDConSec/vsc-print/issues/268#issue-1895035564?

**Comment by PeterWone** [comment]
It means there are man document rendering and conversion tools. [PanDoc ](https://pandoc.org/) was created in 2006 and is one of the most versatile, widely supported and well-known examples.
