### ISSUE TITLE
Colour Scheme for grey scale comments 

### ISSUE THREAD

**Issue by Roler100** [PDConSec/vsc-print#287]
Hi, I have just uploaded the Print extension and am familiarising myself with it. I am experimenting with some of the colour schemes.
I'm looking for a Colour Scheme that prints the '//Comments' only in grayscale. 
Also, is there a colour scheme that prints the code in the same Colour scheme shown on the VC screen?
Thanks,
Martin

**Comment by PeterWone** [comment]
> Hi, I have just uploaded the Print extension and am familiarising myself with it. I am experimenting with some of the colour schemes. I'm looking for a Colour Scheme that prints the '//Comments' only in grayscale. 

Ascetic is a greyscale colour scheme, though it may not be exactly what you want.

Colour schemes are done with CSS stylesheets. Originally they were user installable but changes made to accommodate remote workspaces required a resource namespace unaffected by whether the workspace was local or remote, and therefore colour schemes are now embedded in the extension bundle. It might be possible to restore support for user customisation by providing a mechanism to specify stylesheets URLs for insertion into the head of the generated page.

In the interim you can pull the extension source and add a colour scheme by copying the Ascetic file and modifying it. This would make a great first PR.

>Also, is there a colour scheme that prints the code in the same Colour scheme shown on the VC screen? 

[Why don't we use the same syntax colouring as the editor?](#251 )

**Comment by crcdng** [comment]
> > Hi, I have just uploaded the Print extension and am familiarising myself with it. I am experimenting with some of the colour schemes. I'm looking for a Colour Scheme that prints the '//Comments' only in grayscale.
> 
> Ascetic is a greyscale colour scheme, though it may not be exactly what you want.
> 
> Colour schemes are done with CSS stylesheets. Originally they were user installable but changes made to accommodate remote workspaces required a resource namespace unaffected by whether the workspace was local or remote, and therefore colour schemes are now embedded in the extension bundle. It might be possible to restore support for user customisation by providing a mechanism to specify stylesheets URLs for insertion into the head of the generated page.

+1 to re-add a mechanism for using individual CSS stylesheets or Language grammars (not just for Markdown).

**Comment by PeterWone** [comment]
0.12.5
