### ISSUE TITLE
Printing from the command palette always prints the entire document.

### ISSUE THREAD

**Issue by dc6c** [PDConSec/vsc-print#290]
I can print just the selection by clicking on the printer icon or the context menu, but choosing the command "Printing: Print" from the palette always prints the entire document. Is this by design? I didn't see it mentioned in the manual.

Name: Print
Id: pdconsec.vscode-print
Version: 0.11.18

**Comment by PeterWone** [comment]
It is previously undefined. Command triggered behaviour should be as consistent as possible with mouse triggered behaviour so let's call it a bug.

**Comment by PeterWone** [comment]
FINALLY released this to marketplace.  Please check it works on your machine.

**Comment by dc6c** [comment]
Yep, printing from the palette now handles the selection, thank you! (Print v0.11.28.) I'll close this issue as resolved.
