### ISSUE TITLE
Line numbers start counting from cursor position

### ISSUE THREAD

**Issue by stevenlis** [PDConSec/vsc-print#302]
```
v0.11.19

vscode:
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0
```

I discovered a strange bug where the line numbers start counting from the cursor position when I use the print command instead of starting from 1.

![CS-bAdokOCu@2x](https://github.com/PDConSec/vsc-print/assets/33796896/3eee82c5-c0b5-4969-8128-bafca8a925c0)

![CS-sc5Ych2d@2x](https://github.com/PDConSec/vsc-print/assets/33796896/c343207d-e36e-4485-8264-e3adae04025e)

**Comment by PeterWone** [comment]
I just wanted you to know that we will get this this issue after build pipeline problems are resolved.

**Comment by PeterWone** [comment]
The build pipeline is still a shambles but I am at least now able to do manual publishing to the marketplace.

I think I know what's going on with this bug you found. The line number starting from the start line of the current selection is correct behaviour _for printing a selection_. Now I just have to step through that block of code to see why it's using that.

**Comment by PeterWone** [comment]
It's not happening on my Mac either. I really hate this kind of mystery.

**Comment by PeterWone** [comment]
Steve, can you still reproduce this with the latest release?

**Comment by stevenlis** [comment]
@PeterWone I just tried, and it seems I still do with v0.11.28.
![CS-H3HeSuNk@2x](https://github.com/PDConSec/vsc-print/assets/33796896/6fe244fc-e1ad-4221-845a-6783ed7d1f9e)

**Comment by PeterWone** [comment]
Finally managed to reproduce this when a colleague reproduced a variant of the same problem. It also occurs for unsaved files. For that specific execution path there was an if statement with a faulty condition making it report `selection`. Other code was correcting most of the problem but it was setting the starting line number to the beginning of the selection.
