### ISSUE TITLE
A couple of problems with fresh install experience and help page link

### ISSUE THREAD

**Issue by TimRudy** [PDConSec/vsc-print#306]
1. I get a 404 clicking on "we wrote a manual" link from the Extension page; and from the GitHub README page itself; 3rd, in case of using Ctrl-Shift-P and `Printing: Open the manual`, the error shows in the opened page in VS Code: `manual.md cannot be found`

2. On fresh install, `Extension Settings` did not appear here in the menu - only the other 4 - which was a mystery (resolved by restarting VS Code):

![image](https://github.com/PDConSec/vsc-print/assets/3942818/0da33520-b5d6-4001-93af-1403f4a15ba2)

3. In the Ctrl-Shift-P menu no `print.editorContextMenuItemPosition` shows up for me as I saw in the documentation in a screenshot - only the below `Print` items. Sorry I can't find where I saw that now. Not sure if screenshot or documentation needs to be changed. That setting and all others are found of course under `Settings -> Extensions -> Printing`

![image](https://github.com/PDConSec/vsc-print/assets/3942818/832df596-be86-4d5a-8f1d-cc1dde9becd8)

4. The corner case of using Ctrl-Shift-P on the Extension page (or other similar pages like Settings): then `Printing: Print` gives error:
```
    TypeError: Cannot read properties of undefined (reading 'build')
	at m.<anonymous> (c:\Users\tim\.vscode\extensions\pdconsec.vscode-print-0.11.19\dist\extension.js:2:1294617)
```

Thanks for providing this, awesome

**Comment by PeterWone** [comment]
Hi. Last night's merge rearranged the repo and then failed to release, I'm working on it.

________________________________
From: TimRudy ***@***.***>
Sent: Monday, May 13, 2024 3:01:31 AM
To: PDConSec/vsc-print ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PDConSec/vsc-print] A couple of problems with fresh install experience and help page link (Issue #306)


  1.  I get a 404 clicking on "we wrote a manual" link from the Extension page; and from the GitHub README page itself; 3rd, in case of using Ctrl-Shift-P and Printing: Open the manual, the error shows in the opened page in VS Code: manual.md cannot be found

  2.  On fresh install, Extension Settings did not appear here in the menu - only the other 4 - which was a mystery (resolved by restarting VS Code):

image.png (view on web)<https://github.com/PDConSec/vsc-print/assets/3942818/0da33520-b5d6-4001-93af-1403f4a15ba2>

  1.  In the Ctrl-Shift-P menu no print.editorContextMenuItemPosition shows up for me as I saw in the documentation in a screenshot - only the below Print items. Sorry I can't find where I saw that now. Not sure if screenshot or documentation needs to be changed. That setting and all others are found of course under Settings -> Extensions -> Printing

image.png (view on web)<https://github.com/PDConSec/vsc-print/assets/3942818/832df596-be86-4d5a-8f1d-cc1dde9becd8>

  1.  The corner case of using Ctrl-Shift-P on the Extension page (or other similar pages like Settings): then Printing: Print gives error:

    TypeError: Cannot read properties of undefined (reading 'build')
        at m.<anonymous> (c:\Users\tim\.vscode\extensions\pdconsec.vscode-print-0.11.19\dist\extension.js:2:1294617)


Thanks for providing this, awesome

**Comment by PeterWone** [comment]
Tim, I put a copy of the manual on the original path while we sort out our release problems. I'm marking this as a bug for item 4 and to investigate the other things you've mentioned. Thank you for taking the time to help us maintain quality.

**Comment by TimRudy** [comment]
No problem - Thanks

**Comment by PeterWone** [comment]
Tim, about item 3

`Ctrl`+`Shift`+`P` opens what VS Code calls the palette. The screen snap you saw is of a context menu obtained by right-clicking on the active editor or right-clicking on a file in the File Explorer pane.

I have no control over the palette.

I think that covers all your points now. If you disagree, just comment and I'll re-open this.
