### ISSUE TITLE
Printing multiple files produces page with [object Promise]

### ISSUE THREAD

**Issue by lucky-bai** [PDConSec/vsc-print#335]
Steps to reproduce: Select any 2 files in the explorer and right click -> Print

Result: opens browser page without any source code, just the text "[object Promise]"

![image](https://github.com/user-attachments/assets/209da20c-695a-4a4b-a121-d12da198535a)

Printing a single file works correctly, the bug only occurs when printing multiple files.

Vsc-print version: 0.12.13
VsCode version: 1.91.1

**Comment by PeterWone** [comment]
Thank you for reporting this. It is related to internal changes and a fix will be released shortly.

**Comment by PeterWone** [comment]
Please verify that v0.12.14 rectifies the problem before closing this issue. If it doesn't, please let us know.

**Comment by lucky-bai** [comment]
Yup it's working correctly in 0.12.14 - thanks for the quick fix!
